import { Inter } from "next/font/google";
import "./globals.css";
// import {NextUIProvider} from "@nextui-org/react";
// import {ThemeProvider as NextThemesProvider} from "next-themes";
import Navebar from "@/components/navebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
    
      <body className={inter.className}>
      <Navebar />
          <main className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8 lg:py-24">
            {children}
          </main>
          </body>
      
    </html>
    
   

  );
}
